---

- name: Install all packages
  ansible.builtin.package:
    name: "{{ opendkim_packages }}"
    state: present

- name: Enable service
  ansible.builtin.service:
    name: opendkim
    enabled: yes
