---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

- name: Assertions
  ansible.builtin.assert:
    that:
      - opendkim_domain is defined

- name: Include install.yml
  ansible.builtin.include_tasks: install.yml
- name: Include config.yml
  ansible.builtin.include_tasks: config.yml
- name: Include postfix.yml
  ansible.builtin.include_tasks: postfix.yml

- name: Display DKIM record for DNS
  ansible.builtin.debug:
    msg: "v=DKIM1; k=rsa; p={{ _pubkey.stdout }}"
  tags: molecule-idempotence-notest
