---

- name: Get current smtpd_milter setting  # noqa no-free-form
  ansible.builtin.shell: |
    set -o pipefail
    sed -n '/^smtpd_milter/p' /etc/postfix/main.cf | sed "s/.* = //"
  args:
    executable: /bin/bash
  changed_when: false
  check_mode: false
  register: _milters

- name: Merge smtpd_milters  # noqa jinja[spacing]
  ansible.builtin.set_fact:
    smtpd_milters: "{{ ( _milters.stdout.split(',') + [ opendkim_postfix_settings.smtpd_milters ] ) | unique }}"

- name: Configuring postfix (main.cf)  # noqa jinja[spacing]
  ansible.builtin.lineinfile:
    path: "/etc/postfix/main.cf"
    regexp: "^(#)?{{ item.key }}(\\s)?=.*"
    line: >-
      {%- if item.key == 'smtpd_milters' -%}
      {{ item.key }} = {{ smtpd_milters | join(',') }}
      {%- else -%}
      {{ item.key }} = {{ (item.value | join(', ')) if item.value | type_debug == 'list' else item.value }}
      {%- endif -%}
  loop: "{{ opendkim_postfix_settings | dict2items }}"
  notify: Restart postfix

- name: Add user 'postfix' to group 'opendkim'
  ansible.builtin.user:
    name: postfix
    groups: opendkim
    append: yes
