---

- name: Configuring postfix (main.cf)
  lineinfile:
    path:   /etc/postfix/main.cf
    regexp: "^(#)?{{ item.key }}(\\s)?=.*"
    line:   "{{ item.key }} = {{ (item.value|join(', ')) if item.value|type_debug == 'list' else item.value }}"
  loop: "{{ opendkim_postfix_settings | dict2items }}"
  notify: Restart postfix

- name: Add user 'postfix' to group 'opendkim'
  user:
    name: postfix
    groups: opendkim
    append: yes
