---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    postfix_ipv6: False
    postfix_domain: example.com
    postfix_fqdn: host.example.com
    postfix_ssl_key: "{{ openssl_server_key }}"
    postfix_ssl_chain: "{{ openssl_server_crt }}"
    opendkim_domain: example.com
  roles:
    - deitkrachten.cron
    - deitkrachten.openssl
    - deitkrachten.postfix
  tasks:
    - name: Include role 'ansible-role-opendkim'
      ansible.builtin.include_role:
        name: ansible-role-opendkim
