---

- name: Converge
  hosts: all
  vars:
    opendkim_domain: example.com
  pre_tasks:
    - name: Create 'remote_tmp'
      file:
        path: /root/.ansible/tmp
        state: directory
        mode: "0700"
  roles:
    - postfix
  tasks:
    - name: Include role 'ansible-role-opendkim'
      include_role:
        name: ansible-role-opendkim
